---
title: "import"
author: "Ian Adams"
date: "5/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(readr)
library(lubridate)

here("C:/Users/adams/R/Fitbod")
```


## import

```{r remedy001}

df <- read_csv(here("data", "raw", "WorkoutExport.csv")) %>% janitor::clean_names()

df <- df %>% mutate(weight_lb = round(2.2046*weight_kg, digits = 0)) # convert kg to lb, round to whole number

## date wrangling

df <- rename(df, "date_time" = date)

df$date_time <- as_datetime(df$date_time, tz= "Atlantic/Azores") ## fitbod stores in +0000 tz

df$date_time <- with_tz(df$date_time, tz="America/Denver") ## convert to Mountain Standard Time

df$hour <- hour(df$date_time)
df$day <- day(df$date_time)
df$weekday <- wday(df$date_time, label = TRUE)
df$month <- month(df$date_time, label = TRUE)
df$year <- year(df$date_time)

## Generate total weight per set

df <- df %>% mutate(set_wt = reps*weight_lb)

```
## Bucket exercises?

```{r remedy002}

## Recoding df$exercise into df$exercise_rec
df$exercise_bucket <- df$exercise %>%
  fct_recode(
    "Core" = "Ab Crunch Machine",
    "Squats" = "Air Squats",
    "Warmups" = "Airplane",
    "Warmups" = "Alternating Heel Touch",
    "Warmups" = "Anterior Isometric Neck",
    "Shoulders" = "Arnold Dumbbell Press",
    "Shoulders" = "Around the Worlds",
    "Triceps" = "Assisted Dip",
    "Back" = "Assisted Pull Up",
    "Core" = "Back Extensions",
    "Squats" = "Back Squat",
    "Warmups" = "Backward Arm Circle",
    "Chest" = "Balance Trainer Push Up",
    "Core" = "Balance Trainer Russian Twist",
    "Squats" = "Balance Trainer Squat",
    "Chest" = "Barbell Bench Press",
    "Biceps" = "Barbell Bicep Drag Curl",
    "Biceps" = "Barbell Curl",
    "Chest" = "Barbell Decline Bench Press",
    "Core" = "Barbell Hip Thrust",
    "Chest" = "Barbell Incline Bench Press",
    "Shoulders" = "Barbell Shoulder Press",
    "Traps" = "Barbell Shrug",
    "Warmups" = "Bear Crawl",
    "Shoulders" = "Behind the Neck Push Press",
    "Triceps" = "Bench Dip",
    "Back" = "Bent Over Barbell Row",
    "Biceps" = "Biceps Curl To Shoulder Press",
    "Core" = "Bicycle Crunch",
    "Warmups" = "Bird Dog",
    "Squats" = "Box Front Squat",
    "Squats" = "Box Squat",
    "Squats" = "Bulgarian Split Squat",
    "Warmups" = "Burpee",
    "Warmups" = "Butt Kick",
    "Warmups" = "Butterfly Stretch",
    "Biceps" = "Cable Bicep Curl",
    "Chest" = "Cable Chest Press",
    "Chest" = "Cable Crossover Fly",
    "Biceps" = "Cable Double Bicep Curl",
    "Shoulders" = "Cable Face Pull",
    "Shoulders" = "Cable Lateral Raise",
    "Triceps" = "Cable One Arm Tricep Side Extension",
    "Core" = "Cable Pull Through",
    "Triceps" = "Cable Rope Tricep Extension",
    "Back" = "Cable Row",
    "Core" = "Cable Russian Twists",
    "Shoulders" = "Cable Shoulder External Rotation",
    "Shoulders" = "Cable Shoulder Internal Rotation",
    "Traps" = "Cable Shrugs",
    "Triceps" = "Cable Tricep Pushdown",
    "Triceps" = "Cable Underhand Tricep Pushdown",
    "Shoulders" = "Cable Upright Row",
    "Core" = "Cable Wood Chop",
    "Calves" = "Calf Press",
    "Warmups" = "Cat Cow",
    "Warmups" = "Chest Doorway Stretch",
    "Warmups" = "Chest Expansion",
    "Warmups" = "Child's Pose",
    "Warmups" = "Chin Drop",
    "Biceps" = "Chin Up",
    "Warmups" = "Clam",
    "Chest" = "Close-Grip Bench Press",
    "Biceps" = "Concentration Curl",
    "Warmups" = "Couch Stretch",
    "Warmups" = "Crab Pose",
    "Warmups" = "Crab Reach",
    "Warmups" = "Cross-body Arm Stretch",
    "Core" = "Crunches",
    "Aerobic" = "Cycling",
    "Aerobic" = "Cycling - Stationary",
    "Warmups" = "Dead Bug",
    "Warmups" = "Dead Hang",
    "Core" = "Decline Crunch",
    "Chest" = "Decline Push Up",
    "Triceps" = "Dip",
    "Warmups" = "Downward Dog",
    "Warmups" = "Duck Walk",
    "Back" = "Dumbbell Back Fly",
    "Chest" = "Dumbbell Bench Press",
    "Back" = "Dumbbell Bent Over Row",
    "Biceps" = "Dumbbell Bicep Curl",
    "Chest" = "Dumbbell Decline Bench Press",
    "Chest" = "Dumbbell Fly",
    "Shoulders" = "Dumbbell Front Raise",
    "Chest" = "Dumbbell Incline Bench Press",
    "Chest" = "Dumbbell Incline Fly",
    "Triceps" = "Dumbbell Kickbacks",
    "Legs" = "Dumbbell Lunge",
    "Biceps" = "Dumbbell No Money Curls",
    "Chest" = "Dumbbell Pullover",
    "Shoulders" = "Dumbbell Rear Delt Raise",
    "Deadlift" = "Dumbbell Romanian Deadlift",
    "Back" = "Dumbbell Row",
    "Shoulders" = "Dumbbell Shoulder Press",
    "Shoulders" = "Dumbbell Shoulder Raise",
    "Traps" = "Dumbbell Shrug",
    "Triceps" = "Dumbbell Skullcrusher",
    "Squats" = "Dumbbell Squat",
    "Squats" = "Dumbbell Squat To Shoulder Press",
    "Chest" = "Dumbbell Squeeze Press",
    "Warmups" = "Dumbbell Step Up",
    "Deadlift" = "Dumbbell Stiff Legged Deadlift",
    "Shoulders" = "Dumbbell Upright Row",
    "Warmups" = "Elevated Hip Bridge",
    "Aerobic" = "Elliptical",
    "Core" = "Exercise Ball Crunch",
    "Biceps" = "EZ-Bar Curl",
    "Triceps" = "EZ-Bar Skullcrusher",
    "Warmups" = "Fan Stretch",
    "Warmups" = "Flutter Kicks",
    "Warmups" = "Foam Roll Calves",
    "Warmups" = "Foam Roll Chest",
    "Warmups" = "Foam Roll Glutes",
    "Warmups" = "Foam Roll Hamstrings",
    "Warmups" = "Foam Roll Hip Abductors",
    "Warmups" = "Foam Roll Hip Flexors",
    "Warmups" = "Foam Roll Lats",
    "Warmups" = "Foam Roll Lower Back",
    "Warmups" = "Foam Roll Quadriceps",
    "Warmups" = "Foam Roll Upper Back",
    "Warmups" = "Forward Arm Circle",
    "Shoulders" = "Freemotion Shoulder Press",
    "Warmups" = "Frog Pump",
    "Shoulders" = "Front Plate Raise",
    "Squats" = "Front Squat",
    "Glutes" = "Glute Kickback Machine",
    "Core" = "Good Morning",
    "Squats" = "Hack Squat",
    "Biceps" = "Hammer Curls",
    "Chest" = "Hammerstrength Chest Press",
    "Chest" = "Hammerstrength Decline Chest Press",
    "Back" = "Hammerstrength High Row",
    "Chest" = "Hammerstrength Incline Chest Press",
    "Back" = "Hammerstrength Iso Row",
    "Shoulders" = "Hammerstrength Shoulder Press",
    "Traps" = "Hammerstrength Shrug",
    "Back" = "Handle Band Bent Over Row",
    "Biceps" = "Handle Band Bicep Curl",
    "Core" = "Handle Band Crunch",
    "Shoulders" = "Handle Band Forward Raise",
    "Back" = "Handle Band Lat Pulldown",
    "Shoulders" = "Handle Band Lateral Raise",
    "Chest" = "Handle Band Pec Fly",
    "Shoulders" = "Handle Band Rear Deltoid Fly",
    "Biceps" = "Handle Band Reverse Curl",
    "Back" = "Handle Band Row",
    "Shoulders" = "Handle Band Shoulder Press",
    "Squats" = "Handle Band Squat",
    "Back" = "Handle Band Straight-Arm Pulldown",
    "Triceps" = "Handle Band Tricep Extension",
    "Shoulders" = "Handle Band Upright Row",
    "Power" = "Hang Clean",
    "Power" = "Hang Power Clean",
    "Power" = "Hang Power Snatch",
    "Core" = "Hanging Knee Raise",
    "Core" = "Hanging Leg Raise",
    "Warmups" = "Head Tilt",
    "Warmups" = "Heel Press",
    "Aerobic" = "Hiking",
    "Warmups" = "Hip Flow",
    "Warmups" = "Hip Hinge",
    "Core" = "Hip Thrust",
    "Warmups" = "Inchworm",
    "Triceps" = "Incline Barbell Skull Crusher",
    "Biceps" = "Incline Dumbbell Curl",
    "Back" = "Incline Dumbbell Row",
    "Biceps" = "Incline Hammer Curl",
    "Warmups" = "Jump Squat",
    "Power" = "Kettlebell Clean",
    "Legs" = "Kettlebell Lunge with Rotation",
    "Forearms" = "Kettlebell Single Arm Farmer Walk",
    "Core" = "Kettlebell Sit Up and Press",
    "Squats" = "Kettlebell Sumo Squat",
    "Warmups" = "Knee to Chest Stretch",
    "Warmups" = "Kneeling Hip Flexor Stretch",
    "Squats" = "Kneeling Squat",
    "Shoulders" = "Landmine Press",
    "Back" = "Landmine Row",
    "Back" = "Lat Pulldown",
    "Triceps" = "Lateral Cable Tricep Extension",
    "Warmups" = "Lateral Isometric Neck",
    "Warmups" = "Lateral Lunge Stretch",
    "Shoulders" = "Lateral Raise",
    "Legs" = "Leg Curl",
    "Legs" = "Leg Extension",
    "Legs" = "Leg Press",
    "Legs" = "Leg Pull-In",
    "Core" = "Leg Raise",
    "Biceps" = "Loop Band Bicep Curl",
    "Back" = "Loop Band Chin Up",
    "Shoulders" = "Loop Band Face Pull",
    "Glutes" = "Loop Band Glute Kickback",
    "Core" = "Loop Band Good Morning",
    "Biceps" = "Loop Band Hammer Curl",
    "Back" = "Loop Band High Pull",
    "Chest" = "Loop Band Push Up",
    "Shoulders" = "Loop Band Seated Shoulder Press",
    "Chest" = "Loop Band Single Arm Incline Chest Press",
    "Triceps" = "Loop Band Single Arm Tricep Extension",
    "Chest" = "Loop Band Standing Chest Press",
    "Chest" = "Loop Band Standing Decline Chest Press",
    "Chest" = "Loop Band Standing Incline Chest Press",
    "Triceps" = "Loop Band Standing Tricep Extension",
    "Chest" = "Low Cable Chest Fly",
    "Warmups" = "Lower Back Stretch",
    "Legs" = "Lunge",
    "Legs" = "Lunge Jump",
    "Legs" = "Lunge with Ankle Grab",
    "Warmups" = "Lying Figure Four",
    "Legs" = "Lying Hamstrings Curl",
    "Chest" = "Machine Bench Press",
    "Biceps" = "Machine Bicep Curl",
    "Chest" = "Machine Fly",
    "Legs" = "Machine Hip Abductor",
    "Legs" = "Machine Hip Adductor",
    "Shoulders" = "Machine Lateral Raise",
    "Legs" = "Machine Leg Press",
    "Biceps" = "Machine Preacher Curl",
    "Shoulders" = "Machine Rear Delt Fly",
    "Shoulders" = "Machine Reverse Fly",
    "Back" = "Machine Row",
    "Shoulders" = "Machine Shoulder Press",
    "Shoulders" = "Machine Shoulder Shrug",
    "Triceps" = "Machine Tricep Dip",
    "Triceps" = "Machine Tricep Extension",
    "Core" = "Medicine Ball Full Twist",
    "Chest" = "Mid Cable Crossover Fly",
    "Shoulders" = "Mini Loop Band Alternating Lateral Shoulder Raise",
    "Core" = "Mini Loop Band Hip Thrust",
    "Biceps" = "Mini Loop Band Kneeling Bicep Curl",
    "Shoulders" = "Mini Loop Band Lateral Shoulder Raise",
    "Chest" = "Mini Loop Band Overhead Fly",
    "Warmups" = "Mini Loop Band Plank with Straight Leg Kickback",
    "Shoulders" = "Mini Loop Band Reverse Fly",
    "Triceps" = "Mini Loop Band Tricep Press",
    "Warmups" = "Mountain Climber",
    "Core" = "Oblique Crunch",
    "Forearms" = "Palms-Down Dumbbell Wrist Curl",
    "Forearms" = "Palms-Up Dumbbell Wrist Curl",
    "Chest" = "Pause Barbell Decline Bench Press",
    "Chest" = "Pause Barbell Incline Bench Press",
    "Back" = "Pendlay Row",
    "Warmups" = "Pigeon Pose",
    "Core" = "Plank",
    "Warmups" = "Posterior Isometric Neck",
    "Power" = "Power Clean",
    "Biceps" = "Preacher Curl",
    "Warmups" = "Prone Calf Stretch",
    "Warmups" = "Prone Hip Circle",
    "Warmups" = "Prone Hip Circles Forward",
    "Back" = "Pull Up",
    "Legs" = "Pulse Lunge",
    "Chest" = "Push Press",
    "Chest" = "Push Up",
    "Shoulders" = "PVC Shoulder External Rotation",
    "Back" = "Rack Pulls",
    "Warmups" = "Reach Behind and Open",
    "Back" = "Renegade Row",
    "Biceps" = "Reverse Barbell Curl",
    "Core" = "Reverse Crunch",
    "Biceps" = "Reverse Dumbbell Curl",
    "Back" = "Reverse Grip Barbell Bent Over Row",
    "Back" = "Reverse Grip Pull Down",
    "Warmups" = "Reverse Leg Crossover",
    "Deadlift" = "Romanian Deadlift",
    "Aerobic" = "Rowing",
    "Aerobic" = "Running",
    "Aerobic" = "Running - Treadmill",
    "Core" = "Russian Twist",
    "Back" = "Scapular Pull Up",
    "Warmups" = "Scissor Crossover Kick",
    "Warmups" = "Scissor Kick",
    "Back" = "Seated Back Extension",
    "Shoulders" = "Seated Barbell Shoulder Press",
    "Biceps" = "Seated Dumbbell Curl",
    "Warmups" = "Seated Figure Four",
    "Warmups" = "Seated Forward Bend",
    "Legs" = "Seated Leg Curl",
    "Calves" = "Seated Machine Calf Press",
    "Warmups" = "Seated Neck Release Stretch",
    "Triceps" = "Seated Tricep Press",
    "Warmups" = "Shin Box Hip Flexor",
    "Warmups" = "Shin Box Quad",
    "Back" = "Shotgun Row",
    "Warmups" = "Shoulder Squeeze",
    "Warmups" = "Side Bend Stretch",
    "Core" = "Side Bridge",
    "Shoulders" = "Side Lateral Raise",
    "Shoulders" = "Side Laterals to Front Raise",
    "Warmups" = "Side Leg Raises",
    "Legs" = "Side Lunge",
    "Warmups" = "Single-Leg Glute Bridge with External Rotation",
    "Biceps" = "Single Arm Cable Bicep Curl",
    "Triceps" = "Single Arm Dumbbell Tricep Extension",
    "Forearms" = "Single Arm Farmer Walk",
    "Back" = "Single Arm Landmine Row",
    "Glutes" = "Single Leg Cable Kickback",
    "Glutes" = "Single Leg Glute Bridge",
    "Warmups" = "Single Leg Hip Thrust",
    "Glutes" = "Single Leg Kickback",
    "Deadlift" = "Single Leg Romanian Deadlift",
    "Warmups" = "Single Leg Straight Forward Bend",
    "Core" = "Sit Up",
    "Triceps" = "Skullcrusher",
    "Legs" = "Sled Push",
    "Chest" = "Smith Machine Bench Press",
    "Back" = "Smith Machine Bent Over Row",
    "Calves" = "Smith Machine Calf Raise",
    "Shoulders" = "Smith Machine Overhead Shoulder Press",
    "Squats" = "Smith Machine Squat",
    "Squats" = "Squat with Rotation",
    "Warmups" = "Stability Ball Hyperextension",
    "Aerobic" = "Stair Stepper",
    "Warmups" = "Stance Jack",
    "Shoulders" = "Standing Arnold Press",
    "Calves" = "Standing Barbell Calf Raise",
    "Core" = "Standing Cable Core Twist",
    "Warmups" = "Standing Forward Bend",
    "Warmups" = "Standing Hip Abduction",
    "Warmups" = "Standing Hip Adduction",
    "Warmups" = "Standing Hip Circle",
    "Warmups" = "Standing Hip Flexor Stretch",
    "Calves" = "Standing Machine Calf Press",
    "Legs" = "Static Lunge",
    "Warmups" = "Step Up",
    "Back" = "Stiff-Legged Barbell Good Morning",
    "Deadlift" = "Stiff-Legged Deadlift",
    "Warmups" = "Stir the Pot",
    "Warmups" = "Stomach Vacuum",
    "Back" = "Straight-Arm Pulldown",
    "Glutes" = "Straight Leg Kickback",
    "Deadlift" = "Sumo Deadlift",
    "Core" = "Superman",
    "Core" = "Superman Hold",
    "Core" = "Superman with Scaption",
    "Warmups" = "Supine Back Stretch",
    "Aerobic" = "Swimming",
    "Back" = "T-Bar Row",
    "Warmups" = "Toe Touchers",
    "Core" = "Torture Twist",
    "Back" = "Trap Bar Bent Over Row",
    "Deadlift" = "Trap Bar Deadlift",
    "Traps" = "Trap Bar Shrugs",
    "Triceps" = "Tricep Overhead Extension with Rope",
    "Triceps" = "Tricep Push Up",
    "Warmups" = "Tricep Stretch",
    "Warmups" = "TRX Hip Thrust",
    "Core" = "Tuck Crunch",
    "Warmups" = "Up Dog",
    "Back" = "Upright Row",
    "Back" = "V-Bar Pulldown",
    "Core" = "Vertical Knee Raise",
    "Aerobic" = "Walking",
    "Aerobic" = "Walking - Treadmill",
    "Warmups" = "Walkout to Push Up",
    "Warmups" = "Wall Pectoral Stretch",
    "Warmups" = "Wall Slide Stretch",
    "Back" = "Wide Grip Lat Pulldown",
    "Warmups" = "Wrist Extension Stretch",
    "Biceps" = "Zottman Curl"
  )

```



## export

```{r remedy002}

write_rds(df, file = here("data", "clean", "df_clean.rds"))

write_csv(df, file = here("data", "clean", "df_clean.csv"))

```
